-- DDL generated by Postico 2.0 RC 6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "Week" (
    "Week_Number" integer NOT NULL CHECK ("Week_Number" > 1000) CHECK ("Week_Number" < 9953),
    "Employee_ID" integer NOT NULL REFERENCES "Employee"("Employee_ID"),
    "Work_Quantity" integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "Employee_Week_pkey" ON "Week"("Week_Number" int4_ops,"Employee_ID" int4_ops);
CREATE INDEX "Employee_ID_fkey" ON "Week"("Employee_ID" int4_ops);
