-- DDL generated by Postico 2.0 RC 6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "Delay" (
    "Delay_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Employee_ID" integer NOT NULL REFERENCES "Employee"("Employee_ID"),
    "Delay_Type" boolean NOT NULL,
    "Qt_Hours" double precision NOT NULL CHECK ("Qt_Hours" < 10::double precision),
    "Week_Number" integer NOT NULL DEFAULT 1001 CHECK ("Week_Number" > 1000) CHECK ("Week_Number" < 9953),
    "Day_Of_Week" text NOT NULL CHECK ("Day_Of_Week" = ANY (ARRAY['Monday'::text, 'Tuesday'::text, 'Wednesday'::text, 'Thursday'::text, 'Friday'::text, 'Saturday'::text]))
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "Delays_pkey" ON "Delay"("Delay_ID" int4_ops);
CREATE INDEX "Week_Number_Employee_fkey" ON "Delay"("Employee_ID" int4_ops,"Week_Number" int4_ops);
